### ISSUE TITLE
OME-Zarr containers do not parse when nested inside other paths

### ISSUE THREAD

**Issue by krokicki** [saalfeldlab/n5-ij#71]
When using the "Open N5" dialog if I select an OME-Zarr it parses quickly and correctly:
![Screenshot 2024-03-01 at 1 45 48 PM](https://github.com/saalfeldlab/n5-ij/assets/607324/74b1cbe6-029e-450f-8494-c34fb64cf42c)

But if I create an empty folder and put the OME-Zarr inside, and point "Open N5" to that containing folder, it gets stuck on the "Parsing..." step for several minutes and then eventually just presents the underlying directory structure:

![Screenshot 2024-03-01 at 1 54 44 PM](https://github.com/saalfeldlab/n5-ij/assets/607324/6e1688f6-9662-4708-acd1-e3d34abebe60)

There are no errors generated.

**Comment by bogovicj** [comment]
This is happening because the plugin tries to infer the type of storage format (n5,zarr,hdf5).  In this case, it guessed that the folder you pointed to is an n5 container.  A release we are preparing now will allow you to specify the storage format.

In your case `zarr:/Users/rokickik/Desktop/test`.  However, if the test folder does not contain a `.zgroup` it will fail, since it is not a valid zarr store. Hope that's clear.  I'll leave this open until the next release.

**Comment by krokicki** [comment]
Makes sense. I just want to add that my actual use case is that I have a folder filled with various n5's and zarr's and it would be nice to be able to see everything that can be opened. I expected "Detect datasets" to find both the n5's and the zarr's, but it only finds the n5's right now.

**Comment by bogovicj** [comment]
Gotcha.  Simultaneous listing / interaction with containers of different types is out-of-scope for this plugin.
Maybe in the scope of the tool you started at that hackathon!?

**Comment by bogovicj** [comment]
Closing because out-of-scope.
